export const AmenitiesTypes = {
  Academia: "fitness_center",
  "Aceita animais de estimação": "pets",
  "Aceita cartões de crédito": "credit_score",
  "Ar condicionado": "air",
  Auditório: "stadium",
  Bar: "local_bar",
  "Café da manhã": "free_breakfast",
  Cofre: "lock_person",
  Estacionamento: "local_parking",
  Internet: "wifi",
  Lavanderia: "local_laundry_service",
  Massagens: "air_line_seat_flat",
  Palco: "mic_external_on",
  Piscina: "pool",
  "Play-Ground": "sports_bolleyball",
  "Recepção 24 horas": "local_convenience_store",
  Restaurante: "restaurant",
  "Sala de tv": "live_tv",
  "Sala para Reuniões / Eventos": "meeting_room",
  Sauna: "hot_tub",
  "Serviço de quarto": "room_service",
  "Serviços de Transfer (Aeroporto-Hotel-Aeroporto)":
    "transfer_tithin_a_station",
  Spa: "spa",
};
